/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    events: Event;
    'event-tags': EventTag;
    rockets: Rocket;
    executives: Executive;
    sponsors: Sponsor;
    'sponsor-tiers': SponsorTier;
    'what-we-do': WhatWeDo;
    'journey-items': JourneyItem;
    'team-roles': TeamRole;
    stats: Stat;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-tags': EventTagsSelect<false> | EventTagsSelect<true>;
    rockets: RocketsSelect<false> | RocketsSelect<true>;
    executives: ExecutivesSelect<false> | ExecutivesSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    'sponsor-tiers': SponsorTiersSelect<false> | SponsorTiersSelect<true>;
    'what-we-do': WhatWeDoSelect<false> | WhatWeDoSelect<true>;
    'journey-items': JourneyItemsSelect<false> | JourneyItemsSelect<true>;
    'team-roles': TeamRolesSelect<false> | TeamRolesSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Who can sign in to this admin. Admins manage accounts; editors can change site content but not accounts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the account list so it is not just an email.
   */
  name: string;
  /**
   * Editors can manage all site content. Admins can additionally create, edit and delete accounts. Keep at least two admins so nobody is locked out.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Every image used across the site. Deleting one is blocked while a page still uses it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image in a few words, for screen readers and for when the image fails to load. E.g. "Aurora Mk II on the launch rail".
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Everything listed on the Events page, newest first. Unpublished drafts appear at the top and are not visible on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * The URL for this page: /events/your-slug. Filled in automatically from the title when you first save. Changing it later breaks any link already shared, so only edit it if you mean to.
   */
  slug: string;
  /**
   * Upload a new image or pick one already in the Media library. Optional. Usually the Instagram poster. Leave empty and the card shows a plain UARC panel instead.
   */
  imageMedia?: (number | null) | Media;
  /**
   * Only needed if you are linking an image hosted somewhere else instead of uploading one. Choose a file above and this disappears.
   */
  image?: string | null;
  description: string;
  /**
   * When the event starts. For an event running over more than one day, this is the first day.
   */
  date: string;
  /**
   * Optional. When the event finishes that day. Leave empty and the page shows a start time only.
   */
  endTime?: string | null;
  /**
   * Optional. For one event that runs across more than one day, e.g. an open day on both the Saturday and the Sunday. Add each further day here and the page reads 'September 3 & 4'. For a workshop series with different content each week, use Sessions below instead.
   */
  extraDates?:
    | {
        /**
         * The further day this event also runs on.
         */
        date: string;
        /**
         * Leave empty to run the same hours as the first day. Fill both in only if this day differs.
         */
        startTime?: string | null;
        endTime?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Manage the available tags in the Event Tags collection.
   */
  eventTag?: (number | null) | EventTag;
  /**
   * How people sign up. Choose 'plain text' when there is no link to give, e.g. when the form only lives in the Instagram bio.
   */
  signupType?: ('none' | 'link' | 'text') | null;
  /**
   * Shown as a Sign Up button on the event page, for upcoming events only.
   */
  signupUrl?: string | null;
  /**
   * Shown in place of the button, e.g. "Sign up link in our Instagram bio".
   */
  signupNote?: string | null;
  location?: string | null;
  /**
   * Optional. For a multi-session series (e.g. Level 1 build workshops), add each session. The site puts them in date order for you, so it does not matter what order you add them in. Leave empty for a normal one-off event.
   */
  sessions?:
    | {
        title: string;
        date: string;
        /**
         * Optional. When this session finishes.
         */
        endTime?: string | null;
        /**
         * Optional. For a session that runs across more than one day, e.g. a build workshop held on both the Saturday and the Sunday. It still counts as one session.
         */
        extraDates?:
          | {
              /**
               * The further day this session also runs on.
               */
              date: string;
              /**
               * Leave empty to run the same hours as the session's first day.
               */
              startTime?: string | null;
              endTime?: string | null;
              id?: string | null;
            }[]
          | null;
        description?: string | null;
        /**
         * Optional. Falls back to the event location above if left empty.
         */
        location?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * The labels events can be filed under. Deleting one simply clears it from any event that used it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-tags".
 */
export interface EventTag {
  id: number;
  name: string;
  /**
   * Position in the filter row, starting at 1. Claim a position that is taken and the others shift down automatically.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every rocket shown on the Rockets page. Leave the launch date empty while one is still in development.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rockets".
 */
export interface Rocket {
  id: number;
  name: string;
  /**
   * The URL for this page: /rockets/your-slug. Filled in automatically from the name when you first save. Changing it later breaks any link already shared, so only edit it if you mean to.
   */
  slug: string;
  /**
   * Upload a new image or pick one already in the Media library. Optional. The cover image at the top of the rocket's page. Leave empty and both the card and the page show a plain UARC panel instead.
   */
  imageMedia?: (number | null) | Media;
  /**
   * Only needed if you are linking an image hosted somewhere else instead of uploading one. Choose a file above and this disappears.
   */
  image?: string | null;
  imagePosition?: string | null;
  description?: string | null;
  /**
   * Optional. A YouTube, Instagram or Drive link to the launch footage. Shown as a 'Watch the launch' button on the rocket's page. Leave empty and no button appears.
   */
  launchVideoUrl?: string | null;
  /**
   * Tick to feature this rocket in the Featured Rockets section on the home page. Up to 3 are shown, next launch first. If none are ticked the home page falls back to the most recently launched rockets.
   */
  featured?: boolean | null;
  /**
   * Leave empty while the rocket is still in development. A date in the future marks it as a scheduled launch; a date in the past marks it as launched.
   */
  launchedAt?: string | null;
  /**
   * Entries shown in the Details box on this rocket's page, in this order, laid out in two columns. Leave empty and the box is hidden entirely.
   */
  specs?:
    | {
        /**
         * The small heading, e.g. "Height", "Motor", "Recovery".
         */
        label: string;
        /**
         * The figure itself, including units, e.g. "2.4 m", "Cesaroni J410".
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Additional photos shown in the image gallery on the rocket's detail page, after the cover image above. Drag to reorder.
   */
  gallery?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * The committee, grouped by year. Order sets the position within a year and is kept tidy automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "executives".
 */
export interface Executive {
  id: number;
  name: string;
  role: string;
  bio: string;
  /**
   * Upload a new image or pick one already in the Media library. Optional. Leave empty and the card shows the exec's initials instead.
   */
  photoMedia?: (number | null) | Media;
  /**
   * Only needed if you are linking an image hosted somewhere else instead of uploading one. Choose a file above and this disappears.
   */
  photo?: string | null;
  photoPosition?: string | null;
  /**
   * The committee year this person served. The About page groups execs by this.
   */
  year: number;
  /**
   * Position within this year, starting at 1. Claim a position that is taken and everyone below shifts down automatically on publish.
   */
  order: number;
  linkedinUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Organisations shown on the Sponsors page, grouped into the tier you pick.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  /**
   * Upload a new image or pick one already in the Media library.
   */
  logoMedia?: (number | null) | Media;
  /**
   * Only needed if you are linking an image hosted somewhere else instead of uploading one. Choose a file above and this disappears.
   */
  logo?: string | null;
  /**
   * The sponsor's own website, linked from their logo.
   */
  url: string;
  description?: string | null;
  /**
   * Which section of the sponsors page this sponsor appears in. Manage the available tiers in the Sponsor Tiers collection.
   */
  tier: number | SponsorTier;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * The sections the Sponsors page is split into, in display order. A tier cannot be deleted while sponsors are still in it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsor-tiers".
 */
export interface SponsorTier {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Position on the Sponsors page, starting at 1. Claim a position that is taken and the others shift down automatically.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * The 'What We Do' blocks on the About page, in display order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "what-we-do".
 */
export interface WhatWeDo {
  id: number;
  title: string;
  body?: string | null;
  /**
   * Upload a new image or pick one already in the Media library.
   */
  imageMedia?: (number | null) | Media;
  /**
   * Only needed if you are linking an image hosted somewhere else instead of uploading one. Choose a file above and this disappears.
   */
  image?: string | null;
  imagePosition?: string | null;
  /**
   * Background shade for this block. Alternate between blocks so the page has visible banding.
   */
  variant?: ('background' | 'surface') | null;
  /**
   * Position on the About page, starting at 1. Claim a position that is taken and the others shift down automatically on publish.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * The club's story timeline on the About page, in the order it reads.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-items".
 */
export interface JourneyItem {
  id: number;
  title: string;
  body?: string | null;
  /**
   * Upload a new image or pick one already in the Media library.
   */
  imageMedia?: (number | null) | Media;
  /**
   * Only needed if you are linking an image hosted somewhere else instead of uploading one. Choose a file above and this disappears.
   */
  image?: string | null;
  imagePosition?: string | null;
  /**
   * Background shade for this block. Alternate between blocks so the page has visible banding.
   */
  variant?: ('background' | 'surface') | null;
  /**
   * Position in the timeline, starting at 1. Claim a position that is taken and the others shift down automatically on publish.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * The sub-teams described on the About page, e.g. Structures or Avionics.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-roles".
 */
export interface TeamRole {
  id: number;
  title: string;
  body?: string | null;
  /**
   * Short points listed under the description.
   */
  bullets?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Background shade for this block. Alternate between blocks so the page has visible banding.
   */
  variant?: ('background' | 'surface') | null;
  /**
   * Position on the About page, starting at 1. Claim a position that is taken and the others shift down automatically on publish.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * The headline numbers on the About page, e.g. '150' / 'Active members'.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  /**
   * The figure itself, e.g. "150" or "12+".
   */
  value: string;
  /**
   * What the figure counts, e.g. "Active members".
   */
  label: string;
  /**
   * Position in the row of stats, starting at 1. Claim a position that is taken and the others shift down automatically on publish.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-tags';
        value: number | EventTag;
      } | null)
    | ({
        relationTo: 'rockets';
        value: number | Rocket;
      } | null)
    | ({
        relationTo: 'executives';
        value: number | Executive;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'sponsor-tiers';
        value: number | SponsorTier;
      } | null)
    | ({
        relationTo: 'what-we-do';
        value: number | WhatWeDo;
      } | null)
    | ({
        relationTo: 'journey-items';
        value: number | JourneyItem;
      } | null)
    | ({
        relationTo: 'team-roles';
        value: number | TeamRole;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  imageMedia?: T;
  image?: T;
  description?: T;
  date?: T;
  endTime?: T;
  extraDates?:
    | T
    | {
        date?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  eventTag?: T;
  signupType?: T;
  signupUrl?: T;
  signupNote?: T;
  location?: T;
  sessions?:
    | T
    | {
        title?: T;
        date?: T;
        endTime?: T;
        extraDates?:
          | T
          | {
              date?: T;
              startTime?: T;
              endTime?: T;
              id?: T;
            };
        description?: T;
        location?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-tags_select".
 */
export interface EventTagsSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rockets_select".
 */
export interface RocketsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  imageMedia?: T;
  image?: T;
  imagePosition?: T;
  description?: T;
  launchVideoUrl?: T;
  featured?: T;
  launchedAt?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "executives_select".
 */
export interface ExecutivesSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photoMedia?: T;
  photo?: T;
  photoPosition?: T;
  year?: T;
  order?: T;
  linkedinUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logoMedia?: T;
  logo?: T;
  url?: T;
  description?: T;
  tier?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsor-tiers_select".
 */
export interface SponsorTiersSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "what-we-do_select".
 */
export interface WhatWeDoSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  imageMedia?: T;
  image?: T;
  imagePosition?: T;
  variant?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-items_select".
 */
export interface JourneyItemsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  imageMedia?: T;
  image?: T;
  imagePosition?: T;
  variant?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-roles_select".
 */
export interface TeamRolesSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  bullets?:
    | T
    | {
        value?: T;
        id?: T;
      };
  variant?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide links, contact details and dashboard settings. Changes here affect every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The 'Join' button target, usually the club's AUSA or sign-up page.
   */
  memberJoinUrl?: string | null;
  /**
   * Invite link shown in the footer. Use a Discord invite set to never expire.
   */
  discordUrl?: string | null;
  instagramUrl?: string | null;
  linkedinUrl?: string | null;
  /**
   * Used by every Contact / email link on the site (footer, sponsorship enquiries) and in search-engine structured data. Leave blank to fall back to the built-in default.
   */
  contactEmail?: string | null;
  /**
   * Upload a new image or pick one already in the Media library. Optional. The group photo on the About page.
   */
  execTeamImageMedia?: (number | null) | Media;
  /**
   * Only needed if you are linking an image hosted somewhere else instead of uploading one. Choose a file above and this disappears.
   */
  execTeamImageUrl?: string | null;
  /**
   * Update if the Supabase plan changes. Free tier is 500 MB.
   */
  databaseLimitMb?: number | null;
  /**
   * Free tier is 1024 MB (1 GB).
   */
  storageLimitMb?: number | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  memberJoinUrl?: T;
  discordUrl?: T;
  instagramUrl?: T;
  linkedinUrl?: T;
  contactEmail?: T;
  execTeamImageMedia?: T;
  execTeamImageUrl?: T;
  databaseLimitMb?: T;
  storageLimitMb?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}