import { sql } from "@payloadcms/db-postgres";
import type {
  MigrateDownArgs,
  MigrateUpArgs,
} from "@payloadcms/drizzle/postgres";

/**
 * Turns the single launch video link into a labelled list, so a rocket can
 * carry the launch, an onboard camera and the recovery separately.
 *
 * Any URL already set is carried across as a video labelled "Launch" before
 * the old column is dropped, so nothing is lost.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    CREATE TABLE "rockets_videos" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" varchar PRIMARY KEY NOT NULL,
      "label" varchar,
      "url" varchar
    );
    CREATE TABLE "_rockets_v_version_videos" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" serial PRIMARY KEY NOT NULL,
      "label" varchar,
      "url" varchar,
      "_uuid" varchar
    );

    ALTER TABLE "rockets_videos" ADD CONSTRAINT "rockets_videos_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."rockets"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "_rockets_v_version_videos" ADD CONSTRAINT "_rockets_v_version_videos_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_rockets_v"("id") ON DELETE cascade ON UPDATE no action;

    CREATE INDEX "rockets_videos_order_idx" ON "rockets_videos" USING btree ("_order");
    CREATE INDEX "rockets_videos_parent_id_idx" ON "rockets_videos" USING btree ("_parent_id");
    CREATE INDEX "_rockets_v_version_videos_order_idx" ON "_rockets_v_version_videos" USING btree ("_order");
    CREATE INDEX "_rockets_v_version_videos_parent_id_idx" ON "_rockets_v_version_videos" USING btree ("_parent_id");

    ALTER TABLE "rockets_videos" ENABLE ROW LEVEL SECURITY;
    ALTER TABLE "_rockets_v_version_videos" ENABLE ROW LEVEL SECURITY;

    -- Array row ids are varchars generated by Payload; gen_random_uuid gives
    -- the same shape for these seeded rows.
    INSERT INTO "rockets_videos" ("_order", "_parent_id", "id", "label", "url")
    SELECT 1, id, gen_random_uuid()::varchar, 'Launch', launch_video_url
    FROM "rockets"
    WHERE launch_video_url IS NOT NULL AND btrim(launch_video_url) <> '';

    INSERT INTO "_rockets_v_version_videos" ("_order", "_parent_id", "label", "url")
    SELECT 1, id, 'Launch', version_launch_video_url
    FROM "_rockets_v"
    WHERE version_launch_video_url IS NOT NULL AND btrim(version_launch_video_url) <> '';

    ALTER TABLE "rockets" DROP COLUMN IF EXISTS "launch_video_url";
    ALTER TABLE "_rockets_v" DROP COLUMN IF EXISTS "version_launch_video_url";
  `);
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
    ALTER TABLE "rockets" ADD COLUMN "launch_video_url" varchar;
    ALTER TABLE "_rockets_v" ADD COLUMN "version_launch_video_url" varchar;

    UPDATE "rockets" SET "launch_video_url" = v.url
    FROM "rockets_videos" v WHERE v._parent_id = "rockets".id AND v._order = 1;

    DROP TABLE "rockets_videos" CASCADE;
    DROP TABLE "_rockets_v_version_videos" CASCADE;
  `);
}
